### ISSUE TITLE
Nothing renders on Cinnamon 5.4.12

### ISSUE THREAD

**Issue by FFdhorkin** [Drugwash2/multi-line-taskbar#1]
Really glad to see someone has taken over maintenance on this! Unfortunately, it doesn't seem to be working for me. I can't open the settings page from the list of applets, and nothing renders in my taskbar.

I'm using Cinnamon 5.4.12

Happy to help troubleshoot.

**Comment by Drugwash2** [comment]
Have you **enabled** it after installing? Select it in the applets list and click the big red Plus sign at the bottom. When finished it should be enabled and the settings dialog should become available.
I have Cinnamon 5.4.12 here as well and the applet is working correctly.

**Comment by FFdhorkin** [comment]
Yes, it is enabled.

I am using a fresh install of Linux Mint 21.

I tried opening the looking glass debugger (as per https://stackoverflow.com/questions/14025722/how-to-debug-cinnamon-applet), but even with trace logs enabled, didn't see anything that looked related.

**Comment by Drugwash2** [comment]
Is the default window manager applet disabled? They may clash if both enabled.
Can't see other reason for it not working.

I'm not sure about the branches, this GitHub thing is very weird and uncomfortable to me so there may be something wrong there. The release package should be fine though, I build it straight from my working copy on the test machine.

This may require some in-depth investigation, and it's difficult since you don't get any related errors or warnings. Will try to look into it but can't promise anything.

**Comment by FFdhorkin** [comment]
>Is the default window manager applet disabled?
yes :(

Let me know if there's any way I can help troubleshoot. Happy to, for instance, install a custom debug version, or what not. I would really love this applet to work!

**Comment by Drugwash2** [comment]
There is a value you can toggle to enable a certain level of debugging.
You'd have to edit **applet.js** in applet's folder and modify in line 73 `const debug = false;` to `const debug = true;` and then reload the applet (or Cinnamon entirely).
Applet can be reloaded through Looking Glass; go to Extensons tab, find it in the list,right-click it and select **Reload code**.

Currently I know it has a problem with the tweener effect which doesn't work and throws a warning but at least otherwise the applet works.
I'm not much knowledgeable with Linux -coming from 20+ years of Windows - so it'll be more like trial and error.

**Comment by Drugwash2** [comment]
@FFdhorkin : Unlikely to fix your issue but I just uploaded a new version that fixes some things, you may wanna give it a try.
Please read the release notes, the applet UUID has been changed.

**Comment by FFdhorkin** [comment]
Sorry, somehow I missed your reply a week ago!

Believe it or not, the new version fixed it! I have a new issue, though, so I'll file a new ticket.
